// app/terms-and-conditions/page.tsx
'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';

export default function TermsAndConditions() {
  return (
    <main className="min-h-screen bg-gray-50  text-gray-800 px-6 py-30 md:px-20">
      <motion.section
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-4xl mx-auto space-y-6"
      >
        <h1 className="text-4xl font-bold text-center mb-2">HyperBuds Terms of Use</h1>
        <p className="text-center text-sm text-gray-600 mb-2">
          (Georgia & Florida Version)
        </p>
        <p className="text-center text-sm text-gray-800">
          Effective Date: January 6, 2026
        </p>
        <p>
          By accessing or using HyperBuds, you agree to these Terms of Use.
        </p>

        <h2 className="text-2xl font-semibold mt-8">1. Usage Requirements</h2>
        <ul className="list-disc ml-6 space-y-2">
          <li>You must be at least 13 years old to use HyperBuds</li>
          <li>You are responsible for all activity conducted through your account</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8">2. AI Content Disclosures</h2>
        <ul className="list-disc ml-6 space-y-2">
          <li><strong>Accuracy:</strong> AI is an automated tool, not a human expert. Outputs may be inaccurate, incomplete, or biased.</li>
          <li><strong>No Professional Advice:</strong> Content generated by HyperBuds does not constitute legal, medical, financial, or professional advice.</li>
          <li><strong>Synthetic Media:</strong> If you use HyperBuds to create AI-generated likenesses or synthetic media for commercial use, you are responsible for complying with all applicable disclosure and labeling laws.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8">3. Intellectual Property</h2>
        <ul className="list-disc ml-6 space-y-2">
          <li><strong>Your Content:</strong> You retain ownership of your original inputs. To the extent permitted by law, you own the specific output generated for you.</li>
          <li><strong>License to HyperBuds:</strong> You grant HyperBuds a non-exclusive, worldwide, royalty-free license to process your content solely to operate, maintain, and improve the Services.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8">4. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by applicable law, HyperBuds&apos; total liability for any claim shall not exceed the greater of:
        </p>
        <ul className="list-disc ml-6 space-y-2">
          <li>$100, or</li>
          <li>The total fees paid by you to HyperBuds in the six (6) months preceding the claim.</li>
        </ul>
        <p>
          HyperBuds is not liable for damages arising from reliance on AI-generated content.
        </p>

        <h2 className="text-2xl font-semibold mt-8">5. Governing Law & Dispute Resolution</h2>
        <ul className="list-disc ml-6 space-y-2">
          <li><strong>Governing Law:</strong> These Terms are governed by the laws of the State of Georgia or the State of Florida, without regard to conflict-of-law principles.</li>
          <li><strong>Arbitration:</strong> Any dispute shall be resolved by binding arbitration administered by the American Arbitration Association (AAA).</li>
          <li><strong>Class Action Waiver:</strong> You agree to resolve disputes on an individual basis and waive participation in class or representative actions.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8">6. Contact</h2>
        <p>
          HyperBuds Inc.
          <br />
          [Your Georgia or Florida Business Address]
          <br />
          📧{' '}
          <a href="mailto:support@hyperbuds.com" className="text-blue-600 underline">
            support@hyperbuds.com
          </a>
        </p>

        <div className="border-t border-gray-300 dark:border-gray-700 mt-10 pt-6 text-center">
          <p>
            See our{' '}
            <Link href="/privacy" className="text-blue-600 underline">
              Privacy Policy
            </Link>
          </p>
        </div>
      </motion.section>
    </main>
  );
}
